#!/usr/bin/env python3

# Requires: pip install neurokit2 numpy

import neurokit2 as nk
import numpy as np

FS_HIGH  = 250
FS_IMU   = 20
DURATION = 5
SCALE    = 500

rng = np.random.default_rng(42)

def quantize(sig, scale=SCALE):
    lo, hi = sig.min(), sig.max()
    if hi == lo:
        return np.zeros(len(sig), dtype=np.int16)
    norm = (sig - lo) / (hi - lo) * 2 - 1
    return (norm * scale).astype(np.int16)

n_high = FS_HIGH * DURATION
n_imu  = FS_IMU  * DURATION

eeg1 = quantize(nk.signal_simulate(duration=DURATION, sampling_rate=FS_HIGH, frequency=10, noise=0.05))
eeg2 = quantize(nk.signal_simulate(duration=DURATION, sampling_rate=FS_HIGH, frequency=20, noise=0.05))
ecg  = quantize(nk.ecg_simulate(duration=DURATION, sampling_rate=FS_HIGH, heart_rate=75))

t = np.linspace(0, DURATION, n_imu, endpoint=False)
imu_x = quantize(np.sin(2*np.pi*2.0*t) + 0.1*rng.standard_normal(n_imu))
imu_y = quantize(np.sin(2*np.pi*1.0*t) + 0.05*rng.standard_normal(n_imu))
imu_z = quantize(np.cos(2*np.pi*2.0*t) + 0.1*rng.standard_normal(n_imu))

print("/*")
print(" * dummy_data.h — synthetic biosignal test vectors")
print(" *")
print(f" * EEG1 : {n_high} samples @ {FS_HIGH} Hz, 1 axis  (alpha 10 Hz)")
print(f" * EEG2 : {n_high} samples @ {FS_HIGH} Hz, 1 axis  (beta  20 Hz)")
print(f" * ECG  : {n_high} samples @ {FS_HIGH} Hz, 1 axis  (75 bpm QRS)")
print(f" * IMU  : {n_imu}   samples @ {FS_IMU}  Hz, 3 axes (walk cadence)")
print(" *")
print(" * Generated by tools/gen_dummy_data.py — do not edit by hand.")
print(" */")
print()
print("#ifndef DUMMY_DATA_H")
print("#define DUMMY_DATA_H")
print()
print("#include <stdint.h>")
print()
print(f"#define DUMMY_FS_HIGH  {FS_HIGH}")
print(f"#define DUMMY_FS_IMU   {FS_IMU}")
print(f"#define DUMMY_DURATION {DURATION}")
print(f"#define DUMMY_N_HIGH   {n_high}")
print(f"#define DUMMY_N_IMU    {n_imu}")
print()

def emit_array_1d(name, data):
    n = len(data)
    print(f"static const int16_t {name}[{n}] = {{")
    for start in range(0, n, 16):
        chunk = data[start:start+16]
        vals  = ", ".join(f"{int(v):6d}" for v in chunk)
        comma = "," if start + 16 < n else ""
        print(f"    {vals}{comma}")
    print("};")
    print()

emit_array_1d("dummy_eeg1", eeg1)
emit_array_1d("dummy_eeg2", eeg2)
emit_array_1d("dummy_ecg",  ecg)

print(f"static const int16_t dummy_imu[{n_imu}][3] = {{")
for i in range(n_imu):
    comma = "," if i < n_imu - 1 else ""
    print(f"    {{{int(imu_x[i]):6d}, {int(imu_y[i]):6d}, {int(imu_z[i]):6d}}}{comma}")
print("};")
print()
print("#endif /* DUMMY_DATA_H */")
